# Wine Reviews

## Creating, Reading and Writing

In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("zynicide/wine-reviews")

print("Path to dataset files:", path)

Path to dataset files: /Users/dean/.cache/kagglehub/datasets/zynicide/wine-reviews/versions/4

In [3]:
import pandas as pd
import numpy as np

In [4]:
reviews = pd.read_csv(f"{path}/winemag-data-130k-v2.csv")

In [105]:
reviews.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

## Indexing, Selecting & Assigning

In [6]:
desc = reviews.description
desc

0         Aromas include tropical fruit, broom, brimston...
1         This is ripe and fruity, a wine that is smooth...
2         Tart and snappy, the flavors of lime flesh and...
3         Pineapple rind, lemon pith and orange blossom ...
4         Much like the regular bottling from 2012, this...
                                ...
129966    Notes of honeysuckle and cantaloupe sweeten th...
129967    Citation is given as much as a decade of bottl...
129968    Well-drained gravel soil gives this wine its c...
129969    A dry style of Pinot Gris, this is crisp with ...
129970    Big, rich and off-dry, this is powered by inte...
Name: description, Length: 129971, dtype: object

In [7]:
first_description = reviews.description.iloc[0]
first_description

"Aromas include tropical fruit, broom, brimstone and dried herb. The palate isn't overly expressive, offering unripened apple, citrus and dried sage alongside brisk acidity."

In [8]:
desc.head(10)

0    Aromas include tropical fruit, broom, brimston...
1    This is ripe and fruity, a wine that is smooth...
2    Tart and snappy, the flavors of lime flesh and...
3    Pineapple rind, lemon pith and orange blossom ...
4    Much like the regular bottling from 2012, this...
5    Blackberry and raspberry aromas show a typical...
6    Here's a bright, informal red that opens with ...
7    This dry and restrained wine offers spice in p...
8    Savory dried thyme notes accent sunnier flavor...
9    This has great depth of flavor with its fresh ...
Name: description, dtype: object

In [9]:
reviews.description.iloc[:10]

0    Aromas include tropical fruit, broom, brimston...
1    This is ripe and fruity, a wine that is smooth...
2    Tart and snappy, the flavors of lime flesh and...
3    Pineapple rind, lemon pith and orange blossom ...
4    Much like the regular bottling from 2012, this...
5    Blackberry and raspberry aromas show a typical...
6    Here's a bright, informal red that opens with ...
7    This dry and restrained wine offers spice in p...
8    Savory dried thyme notes accent sunnier flavor...
9    This has great depth of flavor with its fresh ...
Name: description, dtype: object

In [10]:
reviews.loc[:9, "description"]

0    Aromas include tropical fruit, broom, brimston...
1    This is ripe and fruity, a wine that is smooth...
2    Tart and snappy, the flavors of lime flesh and...
3    Pineapple rind, lemon pith and orange blossom ...
4    Much like the regular bottling from 2012, this...
5    Blackberry and raspberry aromas show a typical...
6    Here's a bright, informal red that opens with ...
7    This dry and restrained wine offers spice in p...
8    Savory dried thyme notes accent sunnier flavor...
9    This has great depth of flavor with its fresh ...
Name: description, dtype: object

In [11]:
indices = [1,2,3,5,8]
reviews.iloc[indices]

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
5,5,Spain,Blackberry and raspberry aromas show a typical...,Ars In Vitro,87,15.0,Northern Spain,Navarra,NaN,Michael Schachner,@wineschach,Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...,Tempranillo-Merlot,Tandem
8,8,Germany,Savory dried thyme notes accent sunnier flavor...,Shine,87,12.0,Rheinhessen,NaN,NaN,Anna Lee C. Iijima,NaN,Heinz Eifel 2013 Shine Gewürztraminer (Rheinhe...,Gewürztraminer,Heinz Eifel

In [12]:
indices = [0, 1, 10, 100]
columns = ['country', 'province', 'region_1', 'region_2']
reviews.loc[indices, columns]

      country           province      region_1      region_2
0       Italy  Sicily & Sardinia          Etna           NaN
1    Portugal              Douro           NaN           NaN
10         US         California   Napa Valley          Napa
100        US           New York  Finger Lakes  Finger Lakes

In [13]:
columns = ['country', 'variety']
reviews.loc[:99, columns]

     country                   variety
0      Italy               White Blend
1   Portugal            Portuguese Red
2         US                Pinot Gris
3         US                  Riesling
4         US                Pinot Noir
..       ...                       ...
95    France                     Gamay
96    France                     Gamay
97        US                  Riesling
98     Italy                Sangiovese
99        US  Bordeaux-style Red Blend

[100 rows x 2 columns]

In [14]:
reviews[reviews.country == 'Italy']

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
6,6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
13,13,Italy,This is dominated by oak and oak-driven aromas...,Rosso,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Masseria Setteporte 2012 Rosso (Etna),Nerello Mascalese,Masseria Setteporte
22,22,Italy,Delicate aromas recall white flower and citrus...,Ficiligno,87,19.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Baglio di Pianetto 2007 Ficiligno White (Sicilia),White Blend,Baglio di Pianetto
24,24,Italy,"Aromas of prune, blackcurrant, toast and oak c...",Aynat,87,35.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Canicattì 2009 Aynat Nero d'Avola (Sicilia),Nero d'Avola,Canicattì
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129929,129929,Italy,"This luminous sparkler has a sweet, fruit-forw...",NaN,91,38.0,Veneto,Prosecco Superiore di Cartizze,NaN,NaN,NaN,Col Vetoraz Spumanti NV Prosecco Superiore di...,Prosecco,Col Vetoraz Spumanti
129943,129943,Italy,"A blend of Nero d'Avola and Syrah, this convey...",Adènzia,90,29.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Baglio del Cristo di Campobello 2012 Adènzia R...,Red Blend,Baglio del Cristo di Campobello
129947,129947,Italy,"A blend of 65% Cabernet Sauvignon, 30% Merlot ...",Symposio,90,20.0,Sicily & Sardinia,Terre Siciliane,NaN,Kerin O’Keefe,@kerinokeefe,Feudo Principi di Butera 2012 Symposio Red (Te...,Red Blend,Feudo Principi di Butera
129961,129961,Italy,"Intense aromas of wild cherry, baking spice, t...",NaN,90,30.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,COS 2013 Frappato (Sicilia),Frappato,COS
129962,129962,Italy,"Blackberry, cassis, grilled herb and toasted a...",Sàgana Tenuta San Giacomo,90,40.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Cusumano 2012 Sàgana Tenuta San Giacomo Nero d...,Nero d'Avola,Cusumano

In [15]:
reviews.loc[reviews.country.isin(['Italy'])]

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
6,6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
13,13,Italy,This is dominated by oak and oak-driven aromas...,Rosso,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Masseria Setteporte 2012 Rosso (Etna),Nerello Mascalese,Masseria Setteporte
22,22,Italy,Delicate aromas recall white flower and citrus...,Ficiligno,87,19.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Baglio di Pianetto 2007 Ficiligno White (Sicilia),White Blend,Baglio di Pianetto
24,24,Italy,"Aromas of prune, blackcurrant, toast and oak c...",Aynat,87,35.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Canicattì 2009 Aynat Nero d'Avola (Sicilia),Nero d'Avola,Canicattì
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129929,129929,Italy,"This luminous sparkler has a sweet, fruit-forw...",NaN,91,38.0,Veneto,Prosecco Superiore di Cartizze,NaN,NaN,NaN,Col Vetoraz Spumanti NV Prosecco Superiore di...,Prosecco,Col Vetoraz Spumanti
129943,129943,Italy,"A blend of Nero d'Avola and Syrah, this convey...",Adènzia,90,29.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Baglio del Cristo di Campobello 2012 Adènzia R...,Red Blend,Baglio del Cristo di Campobello
129947,129947,Italy,"A blend of 65% Cabernet Sauvignon, 30% Merlot ...",Symposio,90,20.0,Sicily & Sardinia,Terre Siciliane,NaN,Kerin O’Keefe,@kerinokeefe,Feudo Principi di Butera 2012 Symposio Red (Te...,Red Blend,Feudo Principi di Butera
129961,129961,Italy,"Intense aromas of wild cherry, baking spice, t...",NaN,90,30.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,COS 2013 Frappato (Sicilia),Frappato,COS
129962,129962,Italy,"Blackberry, cassis, grilled herb and toasted a...",Sàgana Tenuta San Giacomo,90,40.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Cusumano 2012 Sàgana Tenuta San Giacomo Nero d...,Nero d'Avola,Cusumano

In [16]:
reviews.loc[
    (reviews.country.isin(['Australia', 'New Zealand']))
    & (reviews.points >= 95)
]

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
345,345,Australia,This wine contains some material over 100 year...,Rare,100,350.0,Victoria,Rutherglen,NaN,Joe Czerwinski,@JoeCz,Chambers Rosewood Vineyards NV Rare Muscat (Ru...,Muscat,Chambers Rosewood Vineyards
346,346,Australia,"This deep brown wine smells like a damp, mossy...",Rare,98,350.0,Victoria,Rutherglen,NaN,Joe Czerwinski,@JoeCz,Chambers Rosewood Vineyards NV Rare Muscadelle...,Muscadelle,Chambers Rosewood Vineyards
348,348,Australia,Deep mahogany. Dried fig and black tea on the ...,Grand,97,100.0,Victoria,Rutherglen,NaN,Joe Czerwinski,@JoeCz,Chambers Rosewood Vineyards NV Grand Muscat (R...,Muscat,Chambers Rosewood Vineyards
349,349,Australia,"RunRig is always complex, and the 2012 doesn't...",RunRig,97,225.0,South Australia,Barossa,NaN,Joe Czerwinski,@JoeCz,Torbreck 2012 RunRig Shiraz-Viognier (Barossa),Shiraz-Viognier,Torbreck
356,356,Australia,"Dusty, firm, powerful: just a few apt descript...",Georgia's Paddock,95,85.0,Victoria,Heathcote,NaN,Joe Czerwinski,@JoeCz,Jasper Hill 2013 Georgia's Paddock Shiraz (Hea...,Shiraz,Jasper Hill
360,360,Australia,Bacon and tapenade elements merge easily on th...,Descendant,95,125.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Torbreck 2012 Descendant Shiraz-Viognier (Baro...,Shiraz-Viognier,Torbreck
365,365,Australia,The Taylor family selected Clare Valley for it...,St. Andrews Single Vineyard Release,95,60.0,South Australia,Clare Valley,NaN,Joe Czerwinski,@JoeCz,Wakefield 2013 St. Andrews Single Vineyard Rel...,Shiraz,Wakefield
14354,14354,Australia,This wine's concentrated dark fruit shows in t...,Old Vine,95,60.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Kaesler 2006 Old Vine Shiraz (Barossa Valley),Shiraz,Kaesler
16538,16538,Australia,"Rich, dense and intense, this is a big, muscul...",The Family Tree,95,65.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Lambert 2013 The Family Tree Shiraz (Barossa V...,Shiraz,Lambert
28573,28573,Australia,Astralis has become one of Australia's top col...,Astralis,95,350.0,South Australia,Clarendon,NaN,Joe Czerwinski,@JoeCz,Clarendon Hills 2005 Astralis Syrah (Clarendon),Syrah,Clarendon Hills
34502,34502,Australia,This prodigious wine showcases Barossa's abili...,The Relic,98,135.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Standish 2006 The Relic Shiraz (Barossa Valley),Shiraz,Standish
34506,34506,Australia,If Standish's Relic is the feminine side of Sh...,The Standish Single Vineyard,96,135.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Standish 2005 The Standish Single Vineyard Shi...,Shiraz,Standish
38988,38988,Australia,Penfolds Bin 707 has leapt in quality over the...,Bin 707,95,200.0,South Australia,South Australia,NaN,Joe Czerwinski,@JoeCz,Penfolds 2009 Bin 707 Cabernet Sauvignon (Sout...,Cabernet Sauvignon,Penfolds
39059,39059,Australia,The Taylor family selected Clare Valley for it...,St. Andrews Single Vineyard Release,95,60.0,South Australia,Clare Valley,NaN,Joe Czerwinski,@JoeCz,Wakefield 2013 St. Andrews Single Vineyard Rel...,Shiraz,Wakefield
39961,39961,Australia,"As unevolved as they are, the dense and multil...",Grange,96,185.0,South Australia,South Australia,NaN,NaN,NaN,Penfolds 1996 Grange Shiraz (South Australia),Shiraz,Penfolds
39962,39962,Australia,"Seamless luxury from stem to stern, this ‘baby...",RWT,95,70.0,South Australia,Barossa Valley,NaN,NaN,NaN,Penfolds 1998 RWT Shiraz (Barossa Valley),Shiraz,Penfolds
45809,45809,Australia,The 2007 Astralis impresses for its combinatio...,Astralis,95,225.0,South Australia,Clarendon,NaN,Joe Czerwinski,@JoeCz,Clarendon Hills 2007 Astralis Syrah (Clarendon),Syrah,Clarendon Hills
56953,56953,Australia,"This inky, embryonic wine deserves to be cella...",Grange,99,850.0,South Australia,South Australia,NaN,Joe Czerwinski,@JoeCz,Penfolds 2010 Grange Shiraz (South Australia),Shiraz,Penfolds
56956,56956,Australia,You may have to scour the country to secure so...,Andelmonde,97,95.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Standish 2012 Andelmonde Shiraz (Barossa Valley),Shiraz,Standish
56957,56957,Australia,Thorn Clarke has taken its Shiraz to a new lev...,Ron Thorn Single Vineyard,96,89.0,South Australia,Barossa,NaN,Joe Czerwinski,@JoeCz,Thorn Clarke 2012 Ron Thorn Single Vineyard Sh...,Shiraz,Thorn Clarke
56959,56959,Australia,Is this the Yin to Grange's Yang? The wines ar...,Hill of Grace,96,820.0,South Australia,Eden Valley,NaN,Joe Czerwinski,@JoeCz,Henschke 2010 Hill of Grace Shiraz (Eden Valley),Shiraz,Henschke
59977,59977,Australia,This is a top example of the classic Australia...,The Peake,96,150.0,South Australia,McLaren Vale,NaN,Joe Czerwinski,@JoeCz,Hickinbotham 2013 The Peake Cabernet-Shiraz (M...,Cabernet-Shiraz,Hickinbotham
59984,59984,Australia,"This is a throwback to those brash, flavor-exu...",One,95,95.0,South Australia,Langhorne Creek,NaN,Joe Czerwinski,@JoeCz,Heartland 2013 One Red (Langhorne Creek),Red Blend,Heartland
67096,67096,Australia,Just a tiny serving of this dark nectar will l...,Calliope Rare,98,86.0,Victoria,Rutherglen,NaN,Joe Czerwinski,@JoeCz,R.L. Buller & Son NV Calliope Rare Tokay (Ruth...,Tokay,R.L. Buller & Son
67101,67101,Australia,"This Muscat is the color of dark coffee, with ...",Rare,95,300.0,Victoria,Rutherglen,NaN,Joe Czerwinski,@JoeCz,Chambers Rosewood Vineyards NV Rare Muscat (Ru...,Muscat,Chambers Rosewood Vineyards
76392,76392,Australia,When the alcohol levels are reined in to appro...,Georgia's Paddock,95,85.0,Victoria,Heathcote,NaN,Joe Czerwinski,@JoeCz,Jasper Hill 2012 Georgia's Paddock Shiraz (Hea...,Shiraz,Jasper Hill
77028,77028,Australia,This has all the size and weight you've come t...,Grange,98,850.0,South Australia,South Australia,NaN,Joe Czerwinski,@JoeCz,Penfolds 2008 Grange Shiraz (South Australia),Shiraz,Penfolds
77036,77036,Australia,RWT (unromantically derived from “Red Wine Tri...,RWT,96,150.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Penfolds 2009 RWT Shiraz (Barossa Valley),Shiraz,Penfolds
77037,77037,Australia,Winemaker Dave Powell is no longer with Torbre...,RunRig,96,225.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Torbreck 2007 RunRig Shiraz-Viognier (Barossa ...,Shiraz-Viognier,Torbreck
77042,77042,Australia,This is likely the most ageworthy Shiraz winem...,Eligo,95,100.0,South Australia,Barossa,NaN,Joe Czerwinski,@JoeCz,John Duval Wines 2010 Eligo Shiraz (Barossa),Shiraz,John Duval Wines
77044,77044,Australia,The fruit for this offering comes from the Gre...,R Reserve,95,105.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Kilikanoon 2009 R Reserve Shiraz (Barossa Valley),Shiraz,Kilikanoon
77046,77046,Australia,With aromas and flavors that range widely from...,The Factor,95,125.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Torbreck 2007 The Factor Shiraz (Barossa Valley),Shiraz,Torbreck
83357,83357,Australia,A throwback to the monster Shiraz style of old...,Grange,96,500.0,South Australia,South Australia,NaN,Joe Czerwinski,@JoeCz,Penfolds 2004 Grange Shiraz (South Australia),Shiraz,Penfolds
84815,84815,Australia,The Factor is always one of Torbreck's biggest...,The Factor,95,125.0,South Australia,Barossa,NaN,Joe Czerwinski,@JoeCz,Torbreck 2012 The Factor Shiraz (Barossa),Shiraz,Torbreck
84816,84816,Australia,"Nashwauk is Kaesler's McLaren Vale project, fi...",Beacon,95,145.0,South Australia,McLaren Vale,NaN,Joe Czerwinski,@JoeCz,Nashwauk 2010 Beacon Shiraz (McLaren Vale),Shiraz,Nashwauk
87128,87128,Australia,"This full-bodied, muscular Shiraz is built for...",Amery Vineyard Block 6,96,120.0,South Australia,McLaren Vale,NaN,Joe Czerwinski,@JoeCz,Kay Brothers 2012 Amery Vineyard Block 6 Shira...,Shiraz,Kay Brothers
87137,87137,Australia,Perhaps the best young wine I've tasted from M...,NaN,95,84.0,Western Australia,Margaret River,NaN,Joe Czerwinski,@JoeCz,Moss Wood 2011 Cabernet Sauvignon (Margaret Ri...,Cabernet Sauvignon,Moss Wood
87143,87143,Australia,"This is wonderfully complex and aromatic, with...",St. Andrews Single Vineyard Release,95,60.0,South Australia,Clare Valley,NaN,Joe Czerwinski,@JoeCz,Wakefield 2012 St. Andrews Single Vineyard Rel...,Shiraz,Wakefield
91851,91851,New Zealand,"This full-bodied, richly tannic wine delivers....",Homage,95,100.0,Hawke's Bay,NaN,NaN,Joe Czerwinski,@JoeCz,Trinity Hill 2013 Homage Syrah (Hawke's Bay),Syrah,Trinity Hill
98386,98386,Australia,One of the more approachable of the d'Arenberg...,Little Venice Single Vineyard,95,85.0,South Australia,McLaren Vale,NaN,Joe Czerwinski,@JoeCz,D'Arenberg 2010 Little Venice Single Vineyard ...,Shiraz,D'Arenberg
99318,99318,Australia,"From vines planted in 1912, this has been an i...",Mount Edelstone Vineyard,95,200.0,South Australia,Eden Valley,NaN,Joe Czerwinski,@JoeCz,Henschke 2014 Mount Edelstone Vineyard Shiraz ...,Shiraz,Henschke
99330,99330,Australia,This Cabernet equivalent to Grange has explode...,Bin 707,95,500.0,South Australia,South Australia,NaN,Joe Czerwinski,@JoeCz,Penfolds 2014 Bin 707 Cabernet Sauvignon (Sout...,Cabernet Sauvignon,Penfolds
99340,99340,Australia,"This rich, opulent wine carries its massive oa...",Les Amis,95,185.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Torbreck 2013 Les Amis Grenache (Barossa Valley),Grenache,Torbreck
109427,109427,Australia,This wine is dark brown in hue with a greenish...,Rare,99,300.0,Victoria,Rutherglen,NaN,Joe Czerwinski,@JoeCz,Chambers Rosewood Vineyards NV Rare Muscadelle...,Muscadelle,Chambers Rosewood Vineyards
109434,109434,Australia,D'Arenberg's lineup of single-vineyard Shiraze...,The Swinging Malaysian Single Vineyard,96,85.0,South Australia,McLaren Vale,NaN,Joe Czerwinski,@JoeCz,D'Arenberg 2010 The Swinging Malaysian Single ...,Shiraz,D'Arenberg
122421,122421,Australia,"Despite this wine's weight and richness, it re...",Amon-Ra Unfiltered,96,110.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Glaetzer 2010 Amon-Ra Unfiltered Shiraz (Baros...,Shiraz,Glaetzer
122430,122430,Australia,These blends are traditional in Australia—they...,Anaperenna,95,80.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Glaetzer 2010 Anaperenna Shiraz-Cabernet Sauvi...,Shiraz-Cabernet Sauvignon,Glaetzer
122507,122507,New Zealand,"This blend of Cabernet Sauvignon (62.5%), Merl...",SQM Gimblett Gravels Cabernets/Merlot,95,79.0,Hawke's Bay,NaN,NaN,Joe Czerwinski,@JoeCz,Squawking Magpie 2014 SQM Gimblett Gravels Cab...,Bordeaux-style Red Blend,Squawking Magpie
122939,122939,Australia,Full-bodied and plush yet vibrant and imbued w...,The Factor,98,125.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Torbreck 2013 The Factor Shiraz (Barossa Valley),Shiraz,Torbreck

## Summary Functions and Maps

In [22]:
reviews.points.describe()

count    129971.000000
mean         88.447138
std           3.039730
min          80.000000
25%          86.000000
50%          88.000000
75%          91.000000
max         100.000000
Name: points, dtype: float64

In [27]:
reviews.points.unique()

array([ 87,  86,  85,  88,  92,  91,  90,  89,  83,  82,  81,  80, 100,
        98,  97,  96,  95,  93,  94,  84,  99])

In [34]:
reviews.points.value_counts()

points
88     17207
87     16933
90     15410
86     12600
89     12226
91     11359
92      9613
85      9530
93      6489
84      6480
94      3758
83      3025
82      1836
95      1535
81       692
96       523
80       397
97       229
98        77
99        33
100       19
Name: count, dtype: int64

In [17]:
reviews.points.median()

np.float64(88.0)

In [18]:
reviews.points.mode()

0    88
Name: points, dtype: int64

In [23]:
reviews.price.describe()

count    120975.000000
mean         35.363389
std          41.022218
min           4.000000
25%          17.000000
50%          25.000000
75%          42.000000
max        3300.000000
Name: price, dtype: float64

In [24]:
reviews.taster_name.describe()

count         103727
unique            19
top       Roger Voss
freq           25514
Name: taster_name, dtype: object

In [30]:
reviews.taster_name.unique()

array(['Kerin O’Keefe', 'Roger Voss', 'Paul Gregutt',
       'Alexander Peartree', 'Michael Schachner', 'Anna Lee C. Iijima',
       'Virginie Boone', 'Matt Kettmann', nan, 'Sean P. Sullivan',
       'Jim Gordon', 'Joe Czerwinski', 'Anne Krebiehl\xa0MW',
       'Lauren Buzzeo', 'Mike DeSimone', 'Jeff Jenssen',
       'Susan Kostrzewa', 'Carrie Dykes', 'Fiona Adams',
       'Christina Pickard'], dtype=object)

In [31]:
reviews.taster_name.value_counts()

taster_name
Roger Voss            25514
Michael Schachner     15134
Kerin O’Keefe         10776
Virginie Boone         9537
Paul Gregutt           9532
Matt Kettmann          6332
Joe Czerwinski         5147
Sean P. Sullivan       4966
Anna Lee C. Iijima     4415
Jim Gordon             4177
Anne Krebiehl MW       3685
Lauren Buzzeo          1835
Susan Kostrzewa        1085
Mike DeSimone           514
Jeff Jenssen            491
Alexander Peartree      415
Carrie Dykes            139
Fiona Adams              27
Christina Pickard         6
Name: count, dtype: int64

In [25]:
reviews.country.describe()

count     129908
unique        43
top           US
freq       54504
Name: country, dtype: object

In [32]:
reviews.country.unique()

array(['Italy', 'Portugal', 'US', 'Spain', 'France', 'Germany',
       'Argentina', 'Chile', 'Australia', 'Austria', 'South Africa',
       'New Zealand', 'Israel', 'Hungary', 'Greece', 'Romania', 'Mexico',
       'Canada', nan, 'Turkey', 'Czech Republic', 'Slovenia',
       'Luxembourg', 'Croatia', 'Georgia', 'Uruguay', 'England',
       'Lebanon', 'Serbia', 'Brazil', 'Moldova', 'Morocco', 'Peru',
       'India', 'Bulgaria', 'Cyprus', 'Armenia', 'Switzerland',
       'Bosnia and Herzegovina', 'Ukraine', 'Slovakia', 'Macedonia',
       'China', 'Egypt'], dtype=object)

In [39]:
reviews.country.value_counts()

country
US                        54504
France                    22093
Italy                     19540
Spain                      6645
Portugal                   5691
Chile                      4472
Argentina                  3800
Austria                    3345
Australia                  2329
Germany                    2165
New Zealand                1419
South Africa               1401
Israel                      505
Greece                      466
Canada                      257
Hungary                     146
Bulgaria                    141
Romania                     120
Uruguay                     109
Turkey                       90
Slovenia                     87
Georgia                      86
England                      74
Croatia                      73
Mexico                       70
Moldova                      59
Brazil                       52
Lebanon                      35
Morocco                      28
Peru                         16
Ukraine                      14
Serbia                       12
Czech Republic               12
Macedonia                    12
Cyprus                       11
India                         9
Switzerland                   7
Luxembourg                    6
Bosnia and Herzegovina        2
Armenia                       2
Slovakia                      1
China                         1
Egypt                         1
Name: count, dtype: int64

In [37]:
reviews.province.describe()

count         129908
unique           425
top       California
freq           36247
Name: province, dtype: object

In [38]:
reviews.province.unique()

array(['Sicily & Sardinia', 'Douro', 'Oregon', 'Michigan',
       'Northern Spain', 'Alsace', 'Rheinhessen', 'California', 'Mosel',
       'Other', 'Mendoza Province', 'Virginia', 'Beaujolais',
       'Colchagua Valley', 'Southern Italy', 'Maule Valley', 'Bordeaux',
       'Maipo Valley', 'Washington', 'Central Italy', 'Champagne',
       'Burgundy', 'South Australia', 'Tejo', 'Rapel Valley', 'Galicia',
       'France Other', 'Tuscany', 'Burgenland', 'New York',
       'Leyda Valley', 'Piedmont', 'Stellenbosch',
       'Simonsberg-Stellenbosch', 'Walker Bay', 'Alentejano',
       'Central Spain', 'Southwest France', 'Aconcagua Valley',
       'Loncomilla Valley', 'Marlborough', 'Northeastern Italy',
       'Casablanca Valley', 'Veneto', 'Western Cape', 'Judean Hills',
       'Alentejo', 'Coastal Region', 'Rhône Valley', 'Galilee',
       'Beira Atlantico', 'Tokaj', 'Leithaberg', 'Santorini', 'Kremstal',
       'Catalonia', 'Recas', "Hawke's Bay", 'Curicó Valley',
       'Limarí Valley', 'Colchagua Costa', 'Languedoc-Roussillon',
       'Provence', 'Victoria', 'Rheingau', 'Tokaji', 'Naoussa',
       'Valle de Guadalupe', 'Central Valley', 'Lontué Valley',
       'Italy Other', 'Weinviertel', 'Thermenregion', 'Niederösterreich',
       'Wagram', 'Loire Valley', 'Lombardy', 'Ontario',
       'Österreichischer Sekt', 'Kamptal', 'Steiermark', 'Südsteiermark',
       'Crete', 'Vinho Verde', 'Idaho', 'Western Australia', 'Levante',
       'Martinborough', 'Central Otago', 'Lisboa', 'Texas',
       'Península de Setúbal', 'Australia Other', 'Tasmania', 'Franken',
       'Ahr', 'Nahe', nan, 'Dealu Mare', 'Port', 'Darling', 'Chile',
       'Südoststeiermark', 'Corinth', 'Halkidiki', 'Thrace', 'Pfalz',
       'Robertson', 'Dan', 'Northwestern Italy', 'Andalucia',
       'Awatere Valley', 'Wiener Gemischter Satz', 'Wachau',
       'Pennsylvania', 'Swartland', 'Dão', 'Wagram-Donauland',
       'Rio Claro', 'Villány', 'Cachapoal Valley', 'Jidvei', 'America',
       'Traisental', 'Bairrada', 'Negev Hills', 'Ribatejano', 'Duriense',
       'New Jersey', 'Beiras', 'Spanish Islands', 'Upper Galilee',
       'Vinho Espumante', 'Epanomi', 'Nemea', 'Peloponnese',
       'Aconcagua Costa', 'Moravia', 'Slovenia', 'Terras do Dão',
       'Beira Interior', 'Panciu', 'Bío Bío Valley', 'Romania',
       'Portuguese Table Wine', 'Minho', 'Missouri', 'New Mexico',
       'Nevada', 'Bucelas', 'Peumo', 'San Antonio', 'Carnuntum',
       'Estremadura', 'Canterbury', 'Spain Other', 'Drama', 'Ella Valley',
       'Moselle Luxembourgeoise', 'Württemberg', 'Baden', 'Pangeon',
       'Elqui Valley', 'Wairau Valley', 'Istria', 'Peljesac', 'Kakheti',
       'Canelones', 'England', 'Marchigue', 'Paarl', 'Durbanville',
       'Weinland Österreich', 'Mantinia', 'Chalkidiki', 'Lebanon',
       'Setubal', 'Mosel-Saar-Ruwer', 'Colorado', 'Pocerina',
       'British Columbia', 'Puente Alto', 'Kumeu', 'Trás-os-Montes',
       'Shomron', 'Rapsani', 'Vienna', 'New South Wales', 'Nelson',
       'Waipara Valley', 'Constantia', 'Arizona', 'Pinto Bandeira',
       'Primorska', 'Moldova', 'Uruguay', 'Zenata', 'South Africa',
       'Massachusetts', 'Ohio', 'Ica', 'San Vicente', 'Nashik',
       'Franschhoek', 'South Island', 'Atlantida', 'Thracian Valley',
       'Tarnave', 'Vipavska Dolina', 'Bekaa Valley', 'Elgin',
       'Itata Valley', 'Table wine', 'Samson', 'Madeira', 'Cyprus',
       'Pageon', 'Vinho Espumante de Qualidade', 'Wellington',
       'Danube River Plains', 'Gisborne', 'Obidos', 'Wairarapa',
       'Armenia', 'Santa Cruz', 'Korčula', 'Viile Timisului', 'Illinois',
       'Aegean', 'Simonsberg-Paarl', 'Juanico', 'Black Sea Coastal',
       'Santa Catarina', 'Overberg', 'Atalanti Valley', 'Sebes',
       'Moscatel de Setúbal', 'Macedonia', 'Ribatejo', 'Germany',
       'Palmela', 'Galil', 'Kras', 'Croatia', 'Waipara', 'Olifants River',
       'Montevideo', 'Campanha', 'Israel', 'Neusiedlersee', 'Hungary',
       'Lolol Valley', 'Cauquenes Valley', 'Groenekloof', 'Alenquer',
       'Goriska Brda', 'Murfatlar', 'Moscatel do Douro',
       'Washington-Oregon', 'New Zealand', 'Serra Gaúcha', 'San Jose',
       'Vale dos Vinhedos', 'Mittelburgenland', 'Lutzville Valley',
       'North Carolina', 'Apalta', 'Malleco', 'Guerrouane', 'Valais',
       'Choapa Valley', 'Georgia', 'Ankara', 'Samos', 'Mittelrhein',
       'Eisenberg', 'Sagrada Familia', 'Austria', 'Mostar', 'Iowa',
       'Tulbagh', 'Cederberg', 'Hemel en Aarde', 'Ceres Plateau',
       'Bot River', 'Patras', 'Korinthia', 'Greece', 'San Clemente',
       'Podunavlje', 'Florina', 'Buin', 'Haut-Judeé', 'Ukraine',
       'Terras do Sado', 'Maipo Valley-Colchagua Valley', 'Brazil',
       'Breedekloof', 'Leyda Valley-Maipo Valley', 'Vermont',
       'Switzerland', 'Waitaki Valley', 'Eger', 'Golan Heights',
       'Fruška Gora', 'Philadelphia', 'Muzla', 'Mátra', 'Pirque', 'Negev',
       'Pitsilia Mountains', 'East Coast', 'Mavrodaphne of Patras',
       'Attica', 'Progreso', 'Elazığ-Diyarbakir', 'Jonkershoek Valley',
       'Tikves', 'Vale Trentino', 'Turkey', 'Waiheke Island', 'Molina',
       'Serra do Sudeste', 'Dalmatian Coast', 'Eilandia',
       'Dealurile Munteniei', 'Thraki', 'Curicó and Maipo Valleys',
       'Štajerska', 'Middle and South Dalmatia', 'Kentucky', 'Župa',
       'Pafos', 'Monemvasia', 'Szekszárd', 'Elazığ', 'Cappadocia',
       'Kutjevo', 'Ismarikos', 'Connecticut', 'Sithonia',
       'Curicó and Leyda Valleys', 'Agioritikos',
       'Casablanca-Curicó Valley', 'Piekenierskloof', 'Elim', 'Malgas',
       'Beotia', 'Algarve', 'Retsina', 'Amindeo', 'Coelemu',
       'Cape South Coast', 'Sopron', 'Bulgaria', 'North Dalmatia',
       'Northern Cape', 'Vinho da Mesa', 'Hvar', 'Cephalonia', 'Lemesos',
       'Cahul', 'Cyclades', 'Breede River Valley', 'Ticino',
       'Vlootenburg', 'Brda', 'Dingač', 'Morocco', 'Achaia',
       'Polkadraai Hills', 'Rhode Island', 'Amyndeon', 'Vânju Mare',
       'Hrvatsko Primorje', 'Central Greece', 'Dolenjska',
       'Österreichischer Perlwein', 'Requinoa',
       'Mavrodaphne de Cephalonie', 'Goumenissa', 'Portugal', 'Messinia',
       'Lakonia', 'Markopoulo', 'Vinho Licoroso', 'Paardeberg',
       'San Antonio de las Minas Valley', 'Krania Olympus', 'Corinthia',
       'Slovenska Istra', 'Commandaria', 'Gladstone', 'Jerusalem Hills',
       'Mount Athos', 'Colares', 'Helderberg',
       'Casablanca & Leyda Valleys', 'Dealurile Hușilor', 'Urla-Thrace',
       'Südburgenland', 'Cape Peninsula', 'Codru Region', 'Sterea Ellada',
       'Muscat of Patras', 'Imathia', 'Alenteo', 'Canada Other',
       'Letrinon', 'Muscat of Kefallonian', 'Thessalikos', 'Hawaii',
       'China', 'Limnos', 'Egypt', 'Viile Timis', 'Devon Valley', 'Krk',
       'Arcadia', 'Cape Agulhas', 'Kathikas', 'Vin de Pays de Velvendo',
       'Landwein Rhein', 'Lesbos', 'Távora-Varosa', 'Neuchâtel'],
      dtype=object)

In [44]:
reviews.province.value_counts()

province
California        36247
Washington         8639
Bordeaux           5941
Tuscany            5897
Oregon             5373
                  ...
Messinia              1
Markopoulo            1
Paardeberg            1
Krania Olympus        1
Neuchâtel             1
Name: count, Length: 425, dtype: int64

### Series

`apply()`

```
Invoke function on values of Series
```

- https://pandas.pydata.org/docs/reference/api/pandas.Series.apply.html#pandas.Series.apply

`map()`

```
Map values of Series according to an input mapping or function
```

- https://pandas.pydata.org/docs/reference/api/pandas.Series.map.html#pandas.Series.map

### DataFrame

`apply()`

```
Apply a function along an axis of the DataFrame
```

- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html#pandas.DataFrame.apply

`map()`

```
Apply a function to a Dataframe elementwise
```

- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.map.html#pandas.DataFrame.map

In [5]:
review_points_mean = reviews.points.mean()
reviews.points.map(lambda p: p - review_points_mean)

0        -1.447138
1        -1.447138
2        -1.447138
3        -1.447138
4        -1.447138
            ...
129966    1.552862
129967    1.552862
129968    1.552862
129969    1.552862
129970    1.552862
Name: points, Length: 129971, dtype: float64

In [6]:
def remean_points(row):
    row.points = row.points - review_points_mean
    return row

reviews.apply(remean_points, axis='columns')

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,-1.447138,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,-1.447138,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,-1.447138,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,-1.447138,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,-1.447138,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,1.552862,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,129967,US,Citation is given as much as a decade of bottl...,NaN,1.552862,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,129968,France,Well-drained gravel soil gives this wine its c...,Kritt,1.552862,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,1.552862,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,1.552862,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [16]:
reviews.country + " - " + reviews.province

0         Italy - Sicily & Sardinia
1                  Portugal - Douro
2                       US - Oregon
3                     US - Michigan
4                       US - Oregon
                    ...
129966              Germany - Mosel
129967                  US - Oregon
129968              France - Alsace
129969              France - Alsace
129970              France - Alsace
Length: 129971, dtype: object

In [34]:
# which wine is the "best bargain"?
# => the wine with the highest points-to-price ratio

bargain_idx = (reviews.points / reviews.price).idxmax()
bargain_wine = reviews.loc[bargain_idx, 'title']

bargain_wine, bargain_idx

('Bandit NV Merlot (California)', 64590)

In [39]:
# tropical or fruity?

n_tropical = reviews.description.map(lambda desc: "tropical" in desc).sum()
n_fruity = reviews.description.map(lambda desc: "fruity" in desc).sum()
descriptor_counts = pd.Series([n_tropical, n_fruity], index=['tropical', 'fruity'], name='counts')

descriptor_counts

tropical    3607
fruity      9090
Name: counts, dtype: int64

## Grouping and Sorting

## Data Types and Missing Values

## Renaming and Combining