# DataFrame Examples

- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame

In [79]:
import pandas as pd
import numpy as np

In [80]:
d1 = {'col1': [1, 2], 'col2': [3, 4]}
f1 = pd.DataFrame(data=d1)
f1

# constructing DataFrame from a dictionary

   col1  col2
0     1     3
1     2     4

In [81]:
f1.dtypes

# inferred dtype is int64

col1    int64
col2    int64
dtype: object

In [82]:
d2 = {'col1': [1, 2], 'col2': [3, 4]}
f2 = pd.DataFrame(data=d2, dtype=np.int8)
f2

# enforce a single dtype

   col1  col2
0     1     3
1     2     4

In [83]:
f2.dtypes

# dtype is int8

col1    int8
col2    int8
dtype: object

In [84]:
d3 = {'col1': [0, 1, 2, 3], 'col2': pd.Series([2, 3], index=[0, 1])}
f3 = pd.DataFrame(data=d3, index=[0, 1, 2, 3])
f3

# constructing DataFrame from a dictionary including Series
# Series index=[0, 1]

   col1  col2
0     0   2.0
1     1   3.0
2     2   NaN
3     3   NaN

In [85]:
d3 = {'col1': [0, 1, 2, 3], 'col2': pd.Series([4, 5], index=[2, 3])}
f3 = pd.DataFrame(data=d3, index=[0, 1, 2, 3])
f3

# constructing DataFrame from a dictionary including Series
# Series index=[2, 3]

   col1  col2
0     0   NaN
1     1   NaN
2     2   4.0
3     3   5.0

In [86]:
d4 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
f4 = pd.DataFrame(data=d4, columns=['a', 'b', 'c'])
f4

# constructing DataFrame from numpy ndarray

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [87]:
d5 = np.array([(0, 1, 2), (3, 4, 5), (6, 7, 8)], dtype=[("a", "?"), ("b", "i4"), ("c", "f4")])
f5 = pd.DataFrame(data=d5, columns=['a', 'b', 'c'])
f5

# constructing DataFrame from a numpy ndarray that has labeled columns
# https://numpy.org/doc/stable/reference/arrays.dtypes.html

       a  b    c
0  False  1  2.0
1   True  4  5.0
2   True  7  8.0

In [88]:
from dataclasses import make_dataclass
Point = make_dataclass("Point", [("x", int), ("y", int)])
pd.DataFrame([Point(0, 0), Point(0, 3), Point(2, 3)], index=['p1', 'p2', 'p3'])

# constructing DataFrame from dataclass

    x  y
p1  0  0
p2  0  3
p3  2  3

In [89]:
ser = pd.Series([1, 2, 3], index=["a", "b", "c"])
df = pd.DataFrame(data=ser, index=["a", "c"])
df

# constructing DataFrame from Series

   0
a  1
c  3

In [90]:
df1 = pd.DataFrame([1, 2, 3], index=["a", "b", "c"], columns=["x"])
df2 = pd.DataFrame(data=df1, index=["a", "c"])
df2

# constructing DataFrame from DataFrame

   x
a  1
c  3